spring.application.name=homework
server.port=8080
app.profile.appname =Ahmed
app.profile.name = Ahmed Almutawa
app.profile.introduction = An aspiring coder and tech enthusiast with a heart of gold
app.profile.theme = Software Engineering
app.profile.facts[0] = Active person
app.profile.facts[1] = prefers sour foods
app.profile.facts[2] = Loves PC gaming
app.profile.facts[3] = Graduated from UOB
app.profile.facts[4] = Currently studying in GA
app.profile.facts[5] = Loves Cars
app.profile.favorite-entity= my pc
app.profile.currently-learning= = Harleys and Motorbikes
app.profile.items.PC = Computer
app.profile.items.Laptop = Computer
app.profile.items.Playstation = Gaming
app.profile.items.psp = Gaming
app.profile.items.xbox = Gaming
app.profile.items.steam = Gaming
app.profile.items.camry = vehicle
app.profile.items.harley = vehicle
app.profile.items.honor = phone
app.profile.items.samsung = tablet 

